flags: {}
packages:
- .
extra-deps:
- attoparsec-0.13.2.2
- bytestring-builder-0.10.8.1.0
- hashable-1.2.7.0
- integer-logarithms-1.0.2.1
- io-streams-1.5.0.1
- network-2.7.0.2
- primitive-0.6.4.0
- scientific-0.3.6.2
- text-1.2.3.0
- vector-0.12.0.1
- zlib-0.6.2
- zlib-bindings-0.1.1.5
resolver: ghc-8.2.2
