flags:
  time-locale-compat:
    old-locale: false
packages:
- .
extra-deps:
- aeson-1.4.0.0
- attoparsec-0.13.2.2
- base-compat-0.10.4
- bytestring-builder-0.10.8.1.0
- dlist-0.8.0.4
- hashable-1.2.7.0
- integer-logarithms-1.0.2.1
- io-streams-1.5.0.1
- network-2.7.0.2
- primitive-0.6.4.0
- random-1.1
- scientific-0.3.6.2
- tagged-0.8.6
- th-abstraction-0.2.8.0
- time-locale-compat-0.1.1.5
- unordered-containers-0.2.9.0
- uuid-types-1.0.3
- vector-0.12.0.1
- zlib-0.6.2
- zlib-bindings-0.1.1.5
resolver: ghc-8.4.3
